Artist.create!(name: "Artist-1", listened: true)
Artist.create!(name: "Artist-2", listened: true)
Artist.create!(name: "Artist-3", listened: true)
Artist.create!(name: "Artist-4", listened: true)
Artist.create!(name: "Artist-5", listened: false)
Artist.create!(name: "Artist-6", listened: false)
Artist.create!(name: "Artist-7", listened: false)
Artist.create!(name: "Artist-8", listened: false)